source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '10.0'
install! 'cocoapods', :deterministic_uuids => false

node_modules_path = '../node_modules'
react_path = File.join(node_modules_path, 'react-native')
yoga_path = File.join(react_path, 'ReactCommon/yoga')
folly_spec_path = File.join(react_path, 'third-party-podspecs/Folly.podspec')
glog_spec_path = File.join(react_path, 'third-party-podspecs/glog.podspec')
double_conversion_spec_path = File.join(react_path, 'third-party-podspecs/DoubleConversion.podspec')

target 'Example' do
  pod 'Pilot/Share', :path => '../', :inhibit_warnings => false

  # As this runs dev, we need the developer web socket
  pod 'React', :path => react_path, :subspecs => %w(DevSupport)
  pod 'yoga', :path => yoga_path
  pod 'Folly', :podspec => folly_spec_path
  pod 'DoubleConversion', :podspec => double_conversion_spec_path
  pod 'glog', :podspec => glog_spec_path
end

plugin 'cocoapods-fix-react-native'